version: 0.0
os: linux
files:
  - source: target/sample-0.0.1-SNAPSHOT.war
    destination: /home/ubuntu/mvn/apache-tomcat-10.1.4/webapps/ # war 파일이 배포될 경로
    overwrite: yes # 덮어쓰기
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall: # 배포가 끝나면 아래 명령어를 실행
    - location: scripts/awsdeploy.sh
      timeout: 60
